services:
  nginx:
    image: nginx:1.28-alpine-slim
    container_name: qlickr-certbot-nginx-container
    env_file:
      - ${PWD}/.env.prod
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PWD}/confs/certbot.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/shared/certfiles/conf:/etc/letsencrypt
      - ${PWD}/shared/certfiles/www:/var/www/certbot
    networks:
      - qlickr-certbot-network
  certbot:
    image: certbot/certbot:latest
    container_name: qlickr-certbot-certbot-container
    volumes:
      - ${PWD}/shared/certfiles/conf:/etc/letsencrypt
      - ${PWD}/shared/certfiles/www:/var/www/certbot
    depends_on:
      - nginx
    networks:
      - qlickr-certbot-network
networks:
  qlickr-certbot-network:
    driver: bridge
