services:
  nginx:
    image: nginx:1.28-alpine-slim
    env_file:
      - ${PWD}/.env.prod
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PWD}/confs/certbot.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/shared/certfiles/conf:/etc/letsencrypt
      - ${PWD}/shared/certfiles/www:/var/www/certbot
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ${PWD}/shared/certfiles/conf:/etc/letsencrypt
      - ${PWD}/shared/certfiles/www:/var/www/certbot
    depends_on:
      - nginx
