services:
  db:
    image: postgres:16-alpine
    container_name: qlickr-dev-db-container
    env_file:
      - ${PWD}/.env.dev
    volumes:
      - ${PWD}/shared/dbfiles:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 3s
      timeout: 15s
      retries: 5
    networks:
      - qlickr-dev-network
  redis:
    image: redis:7-alpine
    container_name: qlickr-dev-redis-container
    env_file:
      - ${PWD}/.env.dev
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ${PWD}/shared/redisfiles:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 15s
      retries: 5
    networks:
      - qlickr-dev-network
  celery:
    image: qlickr-dev-backend:celery
    build:
      context: ${PWD}/backend
      dockerfile: Dockerfile.dev
    container_name: qlickr-dev-celery-container
    env_file:
      - ${PWD}/.env.dev
    command: ["celery", "--app", "project", "worker", "--loglevel=info", "--logfile=/shared/logfiles/celery.log"]
    volumes:
      - ${PWD}/backend:/app
      - ${PWD}/shared/logfiles:/shared/logfiles
    healthcheck:
      test: ["CMD", "celery", "--app", "project", "inspect", "ping"]
      interval: 3s
      timeout: 15s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - qlickr-dev-network
  flower:
    image: qlickr-dev-backend:flower
    build:
      context: ${PWD}/backend
      dockerfile: Dockerfile.dev
    container_name: qlickr-dev-flower-container
    env_file:
      - ${PWD}/.env.dev
    command: ["celery", "--app", "project", "flower", "--uid", "celery"]
    ports:
      - 5555:5555
    volumes:
      - ${PWD}/backend:/app
      - ${PWD}/shared/logfiles:/shared/logfiles
    depends_on:
      celery:
        condition: service_healthy
    networks:
      - qlickr-dev-network
  backend:
    image: qlickr-dev-backend
    build:
      context: ${PWD}/backend
      dockerfile: Dockerfile.dev
    container_name: qlickr-dev-backend-container
    env_file:
      - ${PWD}/.env.dev
    volumes:
      - ${PWD}/backend:/app
      - ${PWD}/shared/staticfiles:/shared/staticfiles
      - ${PWD}/shared/mediafiles:/shared/mediafiles
      - ${PWD}/shared/logfiles:/shared/logfiles
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 3s
      timeout: 15s
      retries: 5
    depends_on:
      celery:
        condition: service_healthy
    networks:
      - qlickr-dev-network
  frontend:
    image: qlickr-dev-frontend
    build:
      context: ${PWD}/frontend
      dockerfile: Dockerfile.dev
    container_name: qlickr-dev-frontend-container
    env_file:
      - ${PWD}/.env.dev
    ports:
      - 5173:5173
    volumes:
      - ${PWD}/frontend/src:/app/src
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/"]
      interval: 3s
      timeout: 15s
      retries: 5
    networks:
      - qlickr-dev-network
  nginx:
    image: nginx:1.28-alpine-slim
    container_name: qlickr-dev-nginx-container
    env_file:
      - ${PWD}/.env.dev
    ports:
      - 80:80
    volumes:
      - ${PWD}/confs/dev.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/shared/staticfiles:/shared/staticfiles
      - ${PWD}/shared/mediafiles:/shared/mediafiles
      - ${PWD}/shared/logfiles:/shared/logfiles
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    networks:
      - qlickr-dev-network
networks:
  qlickr-dev-network:
    driver: bridge
